name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
      - name: Run pre-commit
        uses: pre-commit/action@v3.0.0

  build:
    needs: [lint]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        python-version: ["3.8", "3.12"]
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Checkout code
        uses: nschloe/action-cached-lfs-checkout@v1
      - name: Test with tox
        run: |
          pip install tox
          tox -- --cov meshio --cov-report xml --cov-report term
      - uses: codecov/codecov-action@v3
        if: ${{ matrix.python-version == '3.10' && matrix.os == 'ubuntu-latest' }}
